FROM openjdk:13-alpine
USER root
COPY . /app/authserver
WORKDIR /app/authserver
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN chmod +x ./mvnw
ENTRYPOINT ["./mvnw"]
CMD ["spring-boot:run"]