version:  "3.8"

services:
  authserver:
    build:
      context: "."
      dockerfile: Dockerfile-auth
    ports:
      - 8443:8443
    volumes:
      - type: volume
        source: maven-repo
        target: /root/.m2
      - type: bind
        source: /apps/jwtauthserver
        target: /app/authserver:rw
      - type: bind
        source: /apps/jwtauthserver/logs
        target: /logs/authserver
      - type: bind
        source: /etc/letsencrypt/live/api.satutasmerah.com
        target: /cert
    environment:
      - APP_PORT=8443
      - DB_SCHEMA=authserver
      - TZ=Asia/Singapore
      - SSL_KEYSTORE_LOCATION=/cert/keystore.p12
      - KEY_STORE_PASSWORD=sky-high
      - APP_ID=app-android
    links:
      - database-auth:database

  backend:
    build:
      context: "/apps/satutasmerah/backend-marketplace-stm/."
      dockerfile: /apps/satutasmerah/backend-marketplace-stm/Dockerfile-backend
    ports:
      - 443:8443
    volumes:
      - type: volume
        source: maven-repo
        target: /root/.m2
      - type: bind
        source: /apps/satutasmerah
        target: /app/backend-stm:rw
      - type: bind
        source: /apps/satutasmerah/logs
        target: /logs/backend
      - type: bind
        source: /apps/satutasmerah/datastorage
        target: /app/data
      - type: bind
        source: /etc/letsencrypt/live/api.satutasmerah.com
        target: /cert
    environment:
      - APP_PORT=8443
      - DB_SCHEMA=satutasmerah
      - TZ=Asia/Singapore
      - SSL_KEYSTORE_LOCATION=/cert/keystore.p12
      - KEY_STORE_PASSWORD=sky-high
      - APP_ID=app-android
    links:
      - database-backend:dbbackend

  database-auth:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
    - type: bind
      source: /data/container/live/database/authserver/postgres
#      source: /data/container/beta/database/authserver/postgres
      target: /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=sky-high
      - TZ=Asia/Singapore

  database-backend:
    image: postgres:12-alpine
    ports:
      - 5431:5432
    volumes:
      - type: bind
        source: /data/container/live/database/satutasmerah/postgres
#        source: /data/container/beta/database/satutasmerah/postgres
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=sky-high
      - TZ=Asia/Singapore

  pg-admin:
    image: dpage/pgadmin4
    user: root
    ports:
      - 8181:80
    volumes:
      - type: bind
        source: /data/container/pgadmin
        target: /var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=langi.risky@gmail.com
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_DEFAULT_PASSWORD=sky-high
    logging:
      driver: none

volumes:
  maven-repo:
    external:
      name: maven-repo

