version:  "3.8"

services:
  authserver:
    build: .
    ports:
      - 80:9090
    volumes:
      - type: volume
        source: maven-repo
        target: /root/.m2
      - type: bind
        source: /apps/jwtauthserver
        target: /app:ro
    links:
      - database:database

volumes:
  maven-repo:
    external:
      name: maven-repo
