version:  "3.8"

services:
  authserver:
    build: .
    ports:
      - 80:9090
    volumes:
      - type: volume
        source: maven-repo
        target: /root/.m2
      - type: bind
        source: /apps/jwtauthserver
        target: /app:ro
    links:
      - database:database

  database:
    image: postgres:12-alpine
    ports:
      -5432:5432
    volumes:
    - type: bind
      source: /data/container/database/postgres
      target: /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=sky-high

volumes:
  maven-repo:
    external:
      name: maven-repo
